name: monorepo-compose

# We are delegating all actual definition to the spefic folders
# This is done mostly to allow, ie. Frontend to focus on Frontend
# more than anything else. Caveat with doing it this way
# is lack of a central oversight, and potential conflicts
# with shared resources, mainly the gateway service
# Ie. We have spread out which service is exposed on which (sub)domain
include:
  # Platform provided services
  - platform/services/compose.yaml
  # The User Interface composition
  - frontend/compose.yaml
